import { configureStore, createSlice } from '@reduxjs/toolkit';

const counterSlice = createSlice({
  name: 'counter',
  initialState: { counter: 0 },
  reducers: {
    increment: (state) => { state.counter += 1; },
    decrement: (state) => { state.counter -= 1; },
  },
});

// actions generated by createSlice exported
export const { increment, decrement } = counterSlice.actions;

// Redux store
const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
  },
});

export default store;
